"""统一错误码枚举定义。

为 PPC9 项目提供集中化的错误码枚举，用于跨模块的一致性错误处理。
"""

from __future__ import annotations

from enum import Enum


class ErrorCodes(str, Enum):
    """统一错误码枚举。
    
    所有错误码使用字符串枚举，便于日志记录和API响应。
    """
    
    # 通用错误
    UNKNOWN = "UNKNOWN"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"
    INITIALIZATION_FAILED = "INITIALIZATION_FAILED"
    CLEANUP_FAILED = "CLEANUP_FAILED"
    TIMEOUT = "TIMEOUT"
    
    # 文件操作错误
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_READ_FAILED = "FILE_READ_FAILED"
    FILE_WRITE_FAILED = "FILE_WRITE_FAILED"
    FILE_PERMISSION_DENIED = "FILE_PERMISSION_DENIED"
    INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT"
    ENCODING_DETECTION_FAILED = "ENCODING_DETECTION_FAILED"
    
    # 章节处理错误
    NO_CHAPTERS = "NO_CHAPTERS"
    CHAPTER_PARSE_FAILED = "CHAPTER_PARSE_FAILED"
    CHAPTER_SPLIT_FAILED = "CHAPTER_SPLIT_FAILED"
    EMPTY_CONTENT = "EMPTY_CONTENT"
    
    # TTS 错误
    TTS_ENGINE_ERROR = "TTS_ENGINE_ERROR"
    TTS_SYNTHESIS_FAILED = "TTS_SYNTHESIS_FAILED"
    TTS_CONNECTION_FAILED = "TTS_CONNECTION_FAILED"
    TTS_TIMEOUT = "TTS_TIMEOUT"
    TTS_NO_AUDIO_RECEIVED = "TTS_NO_AUDIO_RECEIVED"
    AUDIO_PROCESSING_FAILED = "AUDIO_PROCESSING_FAILED"
    
    # 网络错误
    NETWORK_ERROR = "NETWORK_ERROR"
    CONNECTION_REFUSED = "CONNECTION_REFUSED"
    CONNECTION_TIMEOUT = "CONNECTION_TIMEOUT"
    HTTP_ERROR = "HTTP_ERROR"
    DNS_RESOLUTION_FAILED = "DNS_RESOLUTION_FAILED"
    
    # 分布式错误
    NODE_UNAVAILABLE = "NODE_UNAVAILABLE"
    TASK_DISTRIBUTION_FAILED = "TASK_DISTRIBUTION_FAILED"
    NODE_COMMUNICATION_ERROR = "NODE_COMMUNICATION_ERROR"
    SCHEDULER_ERROR = "SCHEDULER_ERROR"
    
    # 缓存错误
    CACHE_MISS = "CACHE_MISS"
    CACHE_WRITE_FAILED = "CACHE_WRITE_FAILED"
    CACHE_READ_FAILED = "CACHE_READ_FAILED"
    CACHE_INVALIDATION_FAILED = "CACHE_INVALIDATION_FAILED"
    
    # 执行器错误
    EXECUTOR_ERROR = "EXECUTOR_ERROR"
    EXECUTOR_INITIALIZATION_FAILED = "EXECUTOR_INITIALIZATION_FAILED"
    BATCH_PROCESSING_FAILED = "BATCH_PROCESSING_FAILED"
    QUARANTINE_FAILED = "QUARANTINE_FAILED"
    CANCELLED = "CANCELLED"
    
    # 引擎错误
    ENGINE_ERROR = "ENGINE_ERROR"
    EPUB_GENERATION_FAILED = "EPUB_GENERATION_FAILED"
    EPUB_VALIDATION_FAILED = "EPUB_VALIDATION_FAILED"
